# Wraith Yaml Generated Automagically on : 03/03/2016 @ 13:47:40
# SiteName :secure.bhg.com
browser: "phantomjs" 
domains: 
 secure_bhg_com: https://secure.bhg.com
paths: 
 MM_Acq_Only: /order/?containerName=i4bdbmm20
 Coupon: /order/?containerName=i47gbox25
 MM_Gift_Only: /order/?containerName=i4cgbeg60
 MM_Grouping: /order/?containerName=i54gbmm67
 Gift: /order/?containerName=i55gbti36
 Mailed_Gift: /order/?containerName=bhg_cg_2015_twogifts
 Standard: /order/?containerName=i46gbox80

screen_widths: 
 - 320 
 - 667 
 - 768 
 - 1024 
 - 1280 
 - 1920 
 
resize_or_reload: 'reload' 
history_dir: screenCaptures/secure.bhg.com_base_shots 
directory: screenCaptures/secure.bhg.com_latest_shots 
fuzz: '20%' 
theshold: 5 

gallery: 
 template: 'slideshow_template' 
 thumb_width: 250 
 thumb_height: 250 

mode: diffs_only 
verbose: false 
highligt_color: purple 
phantomjs_options: '--ignore-ssl-errors=true --ssl-protocol=tlsv1'